package main

const (
	classesURI string = "http://grdist.miamioh.edu/php/getClasses.php?dept=%v&num=&inst=&from=2015&to=2015&iid=-1&did=%v&sem=&loc=O"
	deptIdURI  string = "http://grdist.miamioh.edu/php/getDID.php?dept=%s"
)

var subjects = []Subject{
	{Short: "AAA", Title: "Asian/Asian American Studies"},
	{Short: "ACC", Title: "Accountancy"},
	{Short: "ACE", Title: "American Culture & English Prg"},
	{Short: "AER", Title: "Aeronautics"},
	{Short: "AES", Title: "Aerospace Studies"},
	{Short: "AMS", Title: "American Studies"},
	{Short: "ARB", Title: "Arabic"},
	{Short: "ARC", Title: "Architecture & Interior Design"},
	{Short: "ART", Title: "Art"},
	{Short: "ATH", Title: "Anthropology"},
	{Short: "BIO", Title: "Biology"},
	{Short: "BIS", Title: "Integrative Studies"},
	{Short: "BLS", Title: "Business Legal Studies"},
	{Short: "BOT", Title: "Botany"},
	{Short: "BTE", Title: "Business Technology"},
	{Short: "BUS", Title: "Business Analysis"},
	{Short: "BWS", Title: "Black World Studies"},
	{Short: "CAS", Title: "College of Arts and Science"},
	{Short: "CCA", Title: "College of Creative Arts"},
	{Short: "CEC", Title: "Col of Engineering & Computing"},
	{Short: "CHI", Title: "Chinese"},
	{Short: "CHM", Title: "Chemistry & Biochemistry"},
	{Short: "CIT", Title: "Comp Information Technology"},
	{Short: "CJS", Title: "Criminal Justice Studies"},
	{Short: "CLS", Title: "Classics"},
	{Short: "CMS", Title: "Comparative Media Studies"},
	{Short: "COM", Title: "Communication"},
	{Short: "CPB", Title: "Chem, Paper & Biomed Engineer"},
	{Short: "CPE", Title: "Chemical & Paper Engineering"},
	{Short: "CRD", Title: "Civic and Regional Development"},
	{Short: "CSE", Title: "Comp Sci &Software Engineering"},
	{Short: "DST", Title: "Disability Studies"},
	{Short: "EAS", Title: "Engineering & App Science"},
	{Short: "ECE", Title: "Electrical & Computer Engineer"},
	{Short: "ECO", Title: "Economics"},
	{Short: "EDL", Title: "Educational Leadership"},
	{Short: "EDP", Title: "Educational Psychology"},
	{Short: "EDT", Title: "Teacher Education"},
	{Short: "EGM", Title: "Engineering Management"},
	{Short: "EHS", Title: "Education, Health and Society"},
	{Short: "ENG", Title: "English"},
	{Short: "ENT", Title: "Engineering Technology"},
	{Short: "ENV", Title: "Environmental Science"},
	{Short: "ESP", Title: "Entrepreneurship"},
	{Short: "FIN", Title: "Finance"},
	{Short: "FRE", Title: "French"},
	{Short: "FST", Title: "Film Studies"},
	{Short: "FSW", Title: "Family Studies and Social Work"},
	{Short: "GEO", Title: "Geography"},
	{Short: "GER", Title: "German"},
	{Short: "GHS", Title: "Global Health Studies"},
	{Short: "GLG", Title: "Geology"},
	{Short: "GRK", Title: "Greek Language and Literature"},
	{Short: "GSC", Title: "Graduate School Community"},
	{Short: "GTY", Title: "Gerontology"},
	{Short: "HBW", Title: "Hebrew"},
	{Short: "HIN", Title: "Hindi"},
	{Short: "HON", Title: "Honors"},
	{Short: "HST", Title: "History"},
	{Short: "IDS", Title: "Interdisciplinary"},
	{Short: "IES", Title: "Environmental Sciences"},
	{Short: "IMS", Title: "Interactive Media Studies"},
	{Short: "ISA", Title: "Information Systems& Analytics"},
	{Short: "ITL", Title: "Italian"},
	{Short: "ITS", Title: "International Studies"},
	{Short: "JPN", Title: "Japanese"},
	{Short: "JRN", Title: "Journalism"},
	{Short: "KNH", Title: "Kinesiology and Health"},
	{Short: "KOR", Title: "Korean"},
	{Short: "LAS", Title: "Latin American Studies"},
	{Short: "LAT", Title: "Latin Language & Literature"},
	{Short: "LUX", Title: "Luxembourg"},
	{Short: "MAC", Title: "Media and Culture"},
	{Short: "MBI", Title: "Microbiology"},
	{Short: "MGT", Title: "Management"},
	{Short: "MKT", Title: "Marketing"},
	{Short: "MME", Title: "Mechan & Manufact Engineering"},
	{Short: "MTH", Title: "Mathematics"},
	{Short: "MUS", Title: "Music"},
	{Short: "NSC", Title: "Naval Science"},
	{Short: "NSG", Title: "Nursing"},
	{Short: "PCE", Title: "Paper & Chemical Engineering"},
	{Short: "PHL", Title: "Philosophy"},
	{Short: "PHY", Title: "Physics"},
	{Short: "PLW", Title: "Pre-Law Studies"},
	{Short: "PMD", Title: "Premedical Studies"},
	{Short: "POL", Title: "Political Science"},
	{Short: "POR", Title: "Portuguese"},
	{Short: "PSY", Title: "Psychology"},
	{Short: "REL", Title: "Religion, Comparative"},
	{Short: "RUS", Title: "Russian"},
	{Short: "SCA", Title: "School of Creative Arts"},
	{Short: "SJS", Title: "Social Justice Studies"},
	{Short: "SOC", Title: "Sociology"},
	{Short: "SPA", Title: "Speech Pathology & Audiology"},
}
